### ISSUE TITLE
Cairo Development Framework Comparison

### ISSUE THREAD

**Issue by rzmahmood** [immutable/imx-starknet#7]
With many Cairo development frameworks being created for Cairo, there is no clear winner yet. For Solidity, we see frameworks such as Hardhat and Foundry (and combinations of both) being the premier development environment. This issue is to investigate development frameworks on metrics such as:

- Ease of use
- Speed
- Scripting
- Test frameworks
- etc?

Currently, a few development frameworks exist on StarkNet. If I'm missing any, let me know:
- [Nile](https://github.com/OpenZeppelin/nile)
- [Hardhat Plugin](https://github.com/Shard-Labs/starknet-hardhat-plugin)
- [Ape StarkNet](https://github.com/ApeWorX/ape-starknet)
- [Protostar](https://github.com/software-mansion/protostar)

This issue will aim to compile the pros and cons to guide users to an appropriate development framework.

Repo Examples:
- https://github.com/immutable/imx-starknet -> Hardhat Plugin
- https://github.com/OpenZeppelin/cairo-contracts -> Nile
- https://github.com/BibliothecaForAdventurers/realms-contracts -> Protostar
- https://github.com/ApeWorX/project-template -> Ape StarkNet

Current Opinions
- [Immutable X experience with Hardhat Plugin](https://github.com/immutable/imx-starknet/issues/7#issuecomment-1141614549)
- [Protostar vs Nile by Anthony from Only Dust](https://mirror.xyz/onlydust.eth/1yoQch6XFpOjd9VVzZ48bZbpwtmLO2fOqYg7QxzW3DA)

**Comment by rzmahmood** [comment]
Immutable X - Experience with Hardhat Extension:
*Pros*:
1. Easy to use: Creating deployment scripts is very easy and is familiar for those who have used Hardhat. Most blockchain developers are also familiar with the Javascript/Typescript stack so it's easy to pick up. Test cases are also easy to write with Mocha as the test runner.
2. 
*Cons*:
1. Very slow. Our test cases currently take 30 minutes+ to run on a local devnet. In our case, test cases are not idempotent as they would take too long to run, this makes test cases less readable.

**Comment by abdelhamidbakhta** [comment]
> 

I would add the context switching cost between dev and test in the cons of Hardhat (and Nile as well).
With protostar you code in Cairo for both dev and tests. To me it is a very important point because it can also speed up the learning curve of the language because devs will write more Cairo.

**Comment by microbecode** [comment]
> > 
> 
> I would add the context switching cost between dev and test in the cons of Hardhat (and Nile as well). With protostar you code in Cairo for both dev and tests. To me it is a very important point because it can also speed up the learning curve of the language because devs will write more Cairo.

This is interesting. I personally see it the other way around, since Cairo is not the easiest language to work with. I very much prefer writing tests in JS/TS, since everything there "just works" and no need to fight with Cairo weirdness.
An example: working with arrays is a huge pain in Cairo.

**Comment by abdelhamidbakhta** [comment]
> > > 
> > 
> > 
> > I would add the context switching cost between dev and test in the cons of Hardhat (and Nile as well). With protostar you code in Cairo for both dev and tests. To me it is a very important point because it can also speed up the learning curve of the language because devs will write more Cairo.
> 
> This is interesting. I personally see it the other way around, since Cairo is not the easiest language to work with. I very much prefer writing tests in JS/TS, since everything there "just works" and no need to fight with Cairo weirdness. An example: working with arrays is a huge pain in Cairo.

I see your point, that's another way to see it.
Regarding the pain with arrays: we developed a library to provide features like foreach, map, reduce on arrays on Cairo.
For people that are not confortable with recursion and felt pointer arithmetic it can help a lot.
Here is the repo: https://github.com/onlydustxyz/cairo-streams/

Usage example: https://github.com/onlydustxyz/cairo-streams/blob/da156d399a0cb5432465ea31878b43e7c35da258/src/onlydust/stream/tests/test_foreach.cairo#L29
